name: Angular Test

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - id: Checkout
        name: Checkout Repository
        uses: actions/checkout@v4

      - id: Validate_Directories
        name: Validate Directories
        run: |
          if [ ! -d "web" ] || [ ! -d "web/angular" ]; then
            echo "The required directories 'web' or 'web/angular' are missing. Exiting."
            exit 0
          fi

      - id: Setup_Node_20
        name: Set Up Node.js 20
        uses: actions/setup-node@v4
        with:
          cache-dependency-path: web/angular/
          node-version: 20
          cache: 'npm'
          registry-url: ${{ vars.NPM_REPOSITORY_URL }}

      - id: Cache_NPM_Packages
        name: Cache NPM Packages
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-${{ matrix.node-version }}-9.8.0-npmcache-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - id: Install_Angular_CLI
        name: Install Angular CLI
        working-directory: web/angular/
        run: npm install -g @angular/cli@latest

      - id: Run_NPM_Tests
        name: Execute NPM Tests
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_REPOSITORY_TOKEN }}
        working-directory: web/angular/
        run: npm run test
