name: Issue - Opened - Auto Assign
on:
  workflow_call:

jobs:
  auto_assign:
    runs-on: ubuntu-latest
    steps:
      - name: 'Auto-assign issue'
        uses: pozil/auto-assign-issue@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          assignees: ${{ vars.DEFAULT_ISSUE_ASSIGNEE }}
          numOfAssignee: 1