name: Issue - Opened - Test
on:
  issues:
    types: [ opened ]

jobs:
  invoke_issue_opened:
    permissions:
      issues: write
      pull-requests: write
    uses: ir-msob/jima-workflow/.github/workflows/issue-opened.yml@main