# This workflow triggers the auto-assign issue workflow when an issue is opened.

name: Issue - Opened

on:
  workflow_call:
    inputs:
      default_issue_assignee:
        required: true
        type: string
    secrets:
      github_token:
        required: true

jobs:
  invoke_auto_assign_issue:
    # This job invokes the auto-assign issue workflow from another repository
    uses: ir-msob/jima-workflow/.github/workflows/auto-assign-issue.yml@main
    with:
      default_issue_assignee: ${{ inputs.default_issue_assignee }} # The assignee for the issue
    secrets:
      github_token: ${{ secrets.github_token }} # GitHub token for authentication
