# This workflow will build a package using Maven and then publish it to Maven Centeral Repository when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Publish Maven Package to Maven Central Repository
on:
  workflow_call:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - id: Checkout
        name: Checkout
        uses: actions/checkout@v4

      - id: Check_for_POM
        name: Check for POM file
        run: |
          if [ ! -f "pom.xml" ]; then
            echo "No Maven project found. Exiting without action."
            exit 0
          fi

      - id: Setup_JDK_21
        name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - id: Cache_Maven_Packages
        name: Cache Maven Packages
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - id: Install_PGP_Secret_Key
        name: Install PGP Secret Key
        run: |
          # Install PGP Secret Key
          cat <(echo -e "${{ secrets.GPG_SECRET_KEY }}") | gpg --batch --import
          # Verify PGP Secret Key
          gpg --list-secret-keys --keyid-format LONG

      - id: Setup_Maven_settings_xml
        name: Setup Maven settings.xml
        env:
          MAVEN_USERNAME: ${{ secrets.MAVEN_REPOSITORY_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_REPOSITORY_TOKEN }}
        run: |
          mkdir -p ~/.m2
          echo "<settings><servers><server><id>central</id><username>$MAVEN_USERNAME</username><password>$MAVEN_PASSWORD</password></server></servers><profiles><profile><id>release</id><activation><activeByDefault>true</activeByDefault></activation><properties><gpg.executable>gpg2</gpg.executable></properties></profile></profiles></settings>" > ~/.m2/settings.xml

      - id: Deploy_to_Central_Repository
        name: Deploy to Central Repository
        run: |
          mvn \
            --no-transfer-progress \
            --batch-mode \
            -Dgpg.passphrase=${{ secrets.GPG_SECRET_KEY_PASSWORD }} \
            clean deploy -P release
