name: Maven Test
on:
  workflow_call:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - id: Checkout
        name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - id: Fetch_all_branches
        name: Fetch all branches
        run: git fetch --all

      - id: Setup_JDK_21
        name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - id: Cache_Maven_Packages
        name: Cache Maven Packages
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - id: Cache_SonarCloud_Packages
        name: Cache SonarCloud Packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - id: RunـMavenـTests
        name: Run Maven Tests
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn clean verify org.sonarsource.scanner.maven:sonar-maven-plugin:${{ vars.SONAR_MAVEN_PLUGIN_VERSION }}:sonar -Dsonar.host.url=${{ vars.SONAR_HOST_URL }} -Dsonar.java.binaries=${{ vars.SONAR_JAVA_BINARIES }} -Dsonar.java.libraries=${{ vars.SONAR_JAVA_LIBRARIES }} -Dsonar.organization=${{ vars.SONAR_ORGANIZATION }} -Dsonar.projectKey=${{ vars.SONAR_PROJECT_KEY }} -Dsonar.coverage.jacoco.xmlReportPaths=${{ vars.SONAR_COVERAGE_JACOCO_XML_REPORT_PATHS }} -P test,report,coverage