name: Pull Request - main
on:
  workflow_call:
    inputs:
      sonar_host_url:
        required: true
        type: string
      sonar_java_binaries:
        required: true
        type: string
      sonar_java_libraries:
        required: true
        type: string
      sonar_organization:
        required: true
        type: string
      sonar_project_key:
        required: true
        type: string
      sonar_coverage_jacoco_xml_report_paths:
        required: true
        type: string
      sonar_maven_plugin_version:
        required: true
        type: string
    secrets:
      sonar_token:
        required: true
jobs:
  invoke_auto_assign_issue:
    uses: ir-msob/jima-workflow/.github/workflows/auto-assign-issue.yml@main
  invoke_maven_test:
    uses: ir-msob/jima-workflow/.github/workflows/maven-test-and-report.yml@main
    with:
      sonar_host_url: ${{ inputs.sonar_host_url }}
      sonar_java_binaries: ${{ inputs.sonar_java_binaries }}
      sonar_java_libraries: ${{ inputs.sonar_java_libraries }}
      sonar_organization: ${{ inputs.sonar_organization }}
      sonar_project_key: ${{ inputs.sonar_project_key }}
      sonar_coverage_jacoco_xml_report_paths: ${{ inputs.sonar_coverage_jacoco_xml_report_paths }}
      sonar_maven_plugin_version: ${{ inputs.sonar_maven_plugin_version }}
    secrets:
      sonar_token: ${{ secrets.SONAR_TOKEN }}
  invoke_angular_test:
    uses: ir-msob/jima-workflow/.github/workflows/angular-test.yml@main